{"name": " test profile personal_information", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "self = <test.TestRegister object at 0x7ff08a4b4130>\n\n    @allure.title(\" test profile personal_information\")\n    @allure.description(\"Test test profile personal_information\")\n    def test_profile_personal_information(self):\n    \n        self.driver.get(self.base_url)\n        timeout = 30\n        self.close_modal_city()\n        element_present = EC.presence_of_all_elements_located((By.CSS_SELECTOR, 'div.main-slider__slide-wrapper'))\n        WebDriverWait(self.driver, timeout).until(element_present)\n>       self.test_autorization(ifyouwantautorization =1)\n\ntest.py:704: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntest.py:199: in test_autorization\n    WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, \"div.user-panel__wrap\")))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"3536cd23-2863-4fc8-a96b-63b9f1b72b21\")>\nmethod = <selenium.webdriver.support.expected_conditions.presence_of_element_located object at 0x7ff088eaac40>\nmessage = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n/usr/local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py:80: TimeoutException"}, "description": "Test test profile personal_information", "start": 1632398159346, "stop": 1632398196773, "uuid": "97fb6f37-e3fe-4cb3-a14a-751ea6626601", "historyId": "4ba46f6dc3de8031d8740d0021fa7f39", "testCaseId": "b8dfca80b2da2b551bfaf42bd1816caf", "fullName": "test.TestRegister#test_profile_personal_information", "labels": [{"name": "suite", "value": "test"}, {"name": "subSuite", "value": "TestRegister"}, {"name": "host", "value": "9d2fc9ee43bb"}, {"name": "thread", "value": "13-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test"}]}